In [4]:
import pandas as pd
df = pd.read_csv("1745500125912-data.csv")

In [6]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [8]:
df['Actor'][3]

'Ranbir Kapoor'

In [10]:
df[['Actor' , 'IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [12]:
df.iloc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [14]:
df.loc[8,'IMDb']

7.0

In [16]:
df.loc[6,'IMDb']

7.5

In [18]:
df.iloc[7,4] #position

475

In [20]:
df.loc[0:2,["Actor","IMDb","BoxOffice(INR Crore)"]] # label

            Actor  IMDb  BoxOffice(INR Crore)
0  Shah Rukh Khan   7.2                  1050
1     Salman Khan   6.0                   565
2      Aamir Khan   8.4                  2024

In [22]:
df.iloc[0:2,0:2]

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [24]:
df.at[0,'Actor']

'Shah Rukh Khan'

In [26]:
df.iat[0,0]

'Shah Rukh Khan'

In [28]:
df[(df['Year']>=2018) | (df['IMDb']>7)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [32]:
df.query("Year > 2019")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [34]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [ ]:
df.query("Year >= 2018 or IMDb > 7")